object Versions {

    const val coreKtx = "1.9.0"
    const val lifecycleRuntimeKtx ="2.6.2"
    const val activityCompose ="1.8.1"
    const val composeBom ="2023.03.00"
    const val Junit ="4.13.2"
    const val junitTest ="1.1.5"
    const val espressoCore ="3.5.1"
    const val appCompat ="1.6.1"
    const val material ="1.10.0"
    const val hiltAndroid ="2.48"
    const val hiltCompiler ="1.0.0-alpha01"
    const val hiltNavigationCompose ="1.1.0"
    const val retrofit ="2.9.0"
    const val okhttp ="5.0.0-alpha.2"
    const val gsonConverter ="2.9.0"
    const val moshi ="1.13.0"
    const val moshiConverter ="2.9.0"
    const val loggingInterceptor ="4.11.0"
    const val corotines ="1.7.3"
    const val splashScreen ="1.0.0-alpha01"
    const val coil ="2.2.0"
}